srv0:
    server: bigSrv-1
    friend: bigSrv-2
srv1:
    server: bigSrv-2
    friend: bigSrv-3
srv2:
    server: bigSrv-3
    friend: bigSrv-4
srv3:
    server: bigSrv-4
    friend: bigSrv-5
srv4:
    server: bigSrv-5
    friend: bigSrv-1
